In [34]:
# 1. Create a NumPy array with the following values: [1, 2, 3, 4, 5].
import numpy as np
v = np.array([1,2,3,4,5])
print(v)

[1 2 3 4 5]


In [35]:
# Print the shape of the array using the .shape attribute.
v_shape = np.shape(v)
print(v_shape)

(5,)


In [36]:
# Reshape the array into a 2D array with 2 rows and 3 columns.
v1 = np.array([1,2,3,4,5,6])
v1_reshape = v1.reshape(2,3)
print(v1_reshape)

[[1 2 3]
 [4 5 6]]


In [37]:
# 4. Print the shape of the new array.
v1_shape = np.shape(v1)
print(v1_shape)

(6,)


In [38]:
# 5. Create a second NumPy array with the following values: [6, 7, 8, 9, 10].
v2 = np.array([6,7,8,9,10])
print(v2)

[ 6  7  8  9 10]


In [39]:
# 6. Concatenate the two arrays together horizontally.
result = np.hstack((v,v2))

In [40]:
# 7. Print the resulting array.
print(result)

[ 1  2  3  4  5  6  7  8  9 10]


In [46]:
# 8. Compute the resulting array's mean, median, and standard deviation
result_mean = np.mean(result)
print("Mean=",result_mean)

result_median = np.median(result)
print("Median=",result_median)

result_std_dev = np.std(result)
print("Step Deviation=",result_std_dev)

Mean= 5.5
Median= 5.5
Step Deviation= 2.8722813232690143
